### PR TITLE
Hello world pull request

### PR DESCRIPTION
**Pull request by miltonHenschel**
Hello world project

Description:

- Set up linters for HTML and CSS.
- Ignored irrelevant files using .gitignore.
- Added a descriptive README file to the project.

### CODE REVIEW

**Review by Gopxfs — CHANGES_REQUESTED** [review]
# ♻️ STATUS: REQUIRED CHANGES ♻️

## Hi @miltonHenschel 👋,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!



## Highlights :rocket:
✔️ Linters set up correctly.
✔️ Awesome GitHub flow.
✔️ Good folder structure

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions 🗒️  
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @Gopxfs in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Gopxfs** [comment]
As explained on [how to document your work in a professional way](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md): 
image 

Please add a more meaningful title/description to your PR. This will make clearer what you are adding to your project and will be easier to keep track of your activities in the future 😄. 

My tip for you: try to think about what your feature is adding. Is it a hello world? So describe it! Try to be precise and clear with your PR titles/descriptions. You could do something like this for your title: 'Add hello world header' or 'Initial setup'
And something like this for your description:
- Set up linters for HTML and CSS.
- Ignored irrelevant files using .gitignore.
- Added a descriptive README file to the project.

In general, you did a pretty good job with your first PR 😉. Good luck and keep up the good work!

**Comment by miltonHenschel** [comment]
Thanks for the review. Please how do I use the same Pull Request submitted for the first review?

**Review by 1GORDON — APPROVED** [review]
# Status: APPROVED 🟢 

Hi @miltonHenschel ✋



Your project is complete!  There is nothing else to say other than... it's time to merge it: ship it:
Congratulations! :tada: :clap: :clap: :100:

## Highlights!
- Followed Gitflow ✔️ 
- Good commit messages ✔️
- Linters are passing ✔️
- Descriptive Pull request ✔️
- Professional readme ✔️

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me `@1GORDON` if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
